version: '2'

services:
  web:
    image: ficusio/openresty:debian
    depends_on:
      - queue
      - db
    ports:
      - 80:80
    volumes:
      - ./nginx/conf:/opt/openresty/nginx/conf
      - ./nginx/lua:/opt/openresty/nginx/lua
  queue:
    build: ./rabbitmq
    depends_on:
      - db
    environment:
      RABBITMQ_ERLANG_COOKIE: secret_cookie
    ports:
      - 15672
  sink:
    build: ./sink
    depends_on:
      - db
  db:
    image: postgres:latest
